version: '3.8'

services:
  app:
    platform: linux/arm64
    build: .
    image: docker-writting-elastic
    container_name: docker-writting-elastic
    volumes:
      - .:/var/task
    env_file:
      - .env
    ports:
      - "9001:8080"
    networks:
      - lambda_postgres_network

networks:
  lambda_postgres_network:
    driver: bridge
